baseURL = 'http://composcleta.org/'
languageCode = 'es'

title = "Composcleta"
theme = "hugo-universal-theme"
#themesDir = "../.."

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "gl"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    # contentDir = 'content/english'
    languageName = 'English'
    languageCode = 'en-US'
    disabled = true
    weight = 30
  [languages.gl]
    # contentDir = 'content/french'
    languageName = 'Galego'
    weight = 10
  [languages.es]
    # contentDir = 'content/french'
    languageName = 'Español'
    languageCode = 'es-ES'
    disabled = false
    weight = 20

# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 30

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

# style = "default"
style = "default"

# Doc: https://themes.gohugo.io/themes/hugo-universal-theme/
[params]
    # Sobre nosotros
    about_us = """<p><strong>Asociación Cívica Composcleta</strong> é unha asociación sen ánimo de lucro. Nace no ano 2013 coas seguintes fins fundamentais:</p>
        <ul>
            <li> - Promover a bicicleta como medio de transporte urbano.
            <li> - Realizar actividades formativas, informativas, lúdicas, culturais, promocionais e divulgativas sobre mobilidade sustentable.
        </ul>
        <p>Asociación Cívica Composcleta é socia de ConBici - <a href="https://conbici.org">Coordinadora en defensa de la bici</a></p>
        """

    # CONFIGURAR PARA METAS 
    # defaultKeywords = ["devcows", "hugo", "go"]
    # defaultDescription = "Site template made by Devcows using Hugo"
    # default_sharing_image = "img/sharing-default.png"
    # facebook_site = "https://www.facebook.com/GolangSociety/"
    # twitter_site = "GoHugoIO"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Sobre el logo
    disabled_logo = false
    logo_text = "Composcleta"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    address = """<p class="text-uppercase"><strong>Asociación Cívica Composcleta</strong>
        <br>Santiago de Compostela
        <br>15707
        <br>Galicia
        <br>
        <strong>España</strong>
      </p>
      """

    dropdown_mouse_over = true

    # Para habilitar el contact form: https://themes.gohugo.io/themes/hugo-universal-theme/#contact-form
    # email = "your@email.com"
    # contact_form_ajax = false
    # enableRecaptchaInContactForm = true
    # googleRecaptchaKey = "site_key_for_google_recaptcha"

[params.CarouselHomepage]
    enable = true
    path = "id_carousel_path"

# Sección puntos de interés (acción)
[params.features]
    enable = true
    cols = 2
    path = "id_features_path"

[params.testimonials]
    enable = true
    title = "id_testimonials"
    subtitle = "id_testimonials_subtitle"

[params.see_more]
    enable = true
    icon = "far fa-user"
    # title = "Queres acompañarnos? Fasche socia?"
    title = "id_see_more.title"
    subtitle = "id_see_more.subtitle"
    link_url = "/enroll"
    link_text = "id_see_more.link_url"

[params.clients]
    enable = true
    title = 'id_clients.title'
    subtitle = "id_clients.subtitle"

summaryLength = 70

[params.recent_posts]
    enable = true
    title = "id_recent_posts.title"
    # subtitle = "id_recent_posts.subtitle"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[[menu.main]]
    name       = "Home"
    # identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "AboutUs"
    identifier = "menu.home"
    url        = "about"
    weight     = 3

[[menu.main]]
    name       = "Enroll"
    url        = "/enroll"
    weight     = 5

[[menu.main]]
    name       = "proposals"
    url        = "https://proxectos.composcleta.org"
    weight     = 10

# [[menu.main]]
#     name = "Activity"
#     url  = "activity"
#     weight = 11

[[menu.main]]
    name = "Blog"
    url  = "blog"
    weight = 20

[[menu.main]]
    name = "Contact"
    url  = "contact"
    weight = 30

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on bicis@composcleta.org</p>
      <p class="hidden-md hidden-lg">
      <a href="mailto:bicis@composcleta.org" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "Instagram"
    url = "https://www.instagram.com/composcleta/"
    pre = "<i class='fab fa-instagram'></i>"

[[menu.topbar]]
    weight = 2
    name = "Telegram"
    url = "https://t.me/composcleta/"
    pre = "<i class='fab fa-telegram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/composcleta"
    pre = "<i class='fab fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://twitter.com/composcleta"
    pre = "<i class='fab fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Mastodon"
    url = "https://mastodon.social/@composcleta"
    pre = "<i class='fab fa-mastodon'></i>"

[[menu.topbar]]
    weight = 6
    name = "Bluesky"
    url = "https://bsky.app/profile/composcleta.bsky.social"
    pre = "<i class='fab fa-bluesky'></i>"

[[menu.topbar]]
    weight = 7
    name = "Youtube"
    url = "https://www.youtube.com/@asociacioncivicacomposclet924"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.topbar]]
    weight = 8
    name = "Galego"
    url = "/"
    pre = "<img src='/img/flags/galicia.png' alt='Gallego' style='height:15px;'>"

[[menu.topbar]]
    weight = 9
    name = "Español"
    url = "/es/"
    pre = "<img src='/img/flags/espana.png' alt='Español' style='height:15px;'>"


# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  year = "years"

[permalinks]
    # blog = "/blog/:year/:month/:day/:filename/"